name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync and merge upstream
        run: |
          git remote add upstream https://github.com
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
